// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzdyhiwindpgvxwtpiir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZHloaXdpbmRwZ3Z4d3RwaWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjk2NzcsImV4cCI6MjA2MDg0NTY3N30.An0q_bbwTyeTq5z3oRPmYQPuZYRmIRGMSOyCI9CmpFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);